### ISSUE TITLE
Third character in submission defaulting to 0

### ISSUE THREAD

**Issue by jcserv** [James-Livesey/bytle#1]
(spoilers for today’s answer, although i’m not sure if everyone has the same one like wordle but…)

The answer for my bytle was 10110100 and after inputting that the game interprets it as 10010100.

![CADAF463-64BF-45D6-A49A-38510F0A85E1](https://user-images.githubusercontent.com/45128231/151576207-a97c8a89-af8d-466b-ba07-e7c176541d48.jpeg)
![09FE9D65-EF88-486B-B5A8-41D4EDE5F5B1](https://user-images.githubusercontent.com/45128231/151576213-2e912a1f-51d2-44ce-8ff6-3366a245e7b4.jpeg)

**Comment by James-Livesey** [comment]
Ah, this one has caught a lot of people — the challenge is to enter a base-10 number (eg. 89), and not binary, which is subsequently then converted to binary when it is added as a row. A bit different to the mechanics of normal Wordle-like games in a way, but just something to make it a bit harder. Hope this helps!

PS: Yup, everyone gets the same value to guess every day, much like Wordle!

**Comment by jcserv** [comment]
Ah gotcha!

**Comment by James-Livesey** [comment]
Just added a fix that clarifies the instructions on how to play the game with issue #3. Hopefully it should be easier for people to play now!
